DiziFilmSatis/Controllers/SatisController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using DiziFilmSatis.Models.Entity;
namespace DiziFilmSatis.Controllers
{
    public class SatisController : Controller
    {
        // GET: Satis
        Db_DiziFilmSatisEntities db = new Db_DiziFilmSatisEntities();
        public ActionResult Index(int sayfa=1)
        {
            var satis = db.Tbl_Filmdizi.ToList().ToPagedList(sayfa,3);
            return View(satis);
        }
        public ActionResult Yonetmen(int id)
        {
            var bul = db.Tbl_Yonetmen.FirstOrDefault(x => x.Id == id);
            return RedirectToAction("Detay", "Yonetmen", bul);
        }
        public ActionResult Detay(int id)
        {
            var bul = db.Tbl_Filmdizi.Find(id);
            return View("Detay", bul);
        }
        [HttpGet]
        public ActionResult Ekle()
        {
            List<SelectListItem> kat = (from x in db.Tbl_Kategori.Where(x => x.Durum == true).ToList()
                                        select new SelectListItem
                                        {
                                            Value = x.Id.ToString(),
                                            Text = x.Katad
                                        }).ToList();
            ViewBag.kat = kat;

            List<SelectListItem> tur = (from x in db.Tbl_Tur.Where(x => x.Durum == true).ToList()
                                        select new SelectListItem
                                        {
                                            Value = x.Id.ToString(),
                                            Text = x.Turad
                                        }).ToList();
            ViewBag.tur = tur;

            List<SelectListItem> yonetmen = (from x in db.Tbl_Yonetmen.Where(x => x.Durum == true).ToList()
                                             select new SelectListItem
                                             {
                                                 Value = x.Id.ToString(),
                                                 Text = x.Ad + " " + x.Soyad
                                             }).ToList();
            ViewBag.yonet = yonetmen;
            return View();
        }
        [HttpPost]
        public ActionResult Ekle(Tbl_Filmdizi p)
        {
            var kat = db.Tbl_Kategori.Where(x => x.Id == p.Tbl_Kategori.Id).FirstOrDefault();
            var tur = db.Tbl_Tur.Where(x => x.Id == p.Tbl_Tur.Id).FirstOrDefault();
            var yonet = db.Tbl_Yonetmen.Where(x => x.Id == p.Tbl_Yonetmen.Id).FirstOrDefault();
            p.Tbl_Kategori = kat;
            p.Tbl_Tur = tur;
            p.Tbl_Yonetmen = yonet;
            p.Durum = true;
            db.Tbl_Filmdizi.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Guncelle(int id)
        {
            List<SelectListItem> kat = (from x in db.Tbl_Kategori.Where(x => x.Durum == true).ToList()
                                        select new SelectListItem
                                        {
                                            Text = x.Katad,
                                            Value = x.Id.ToString()
                                        }).ToList();
            ViewBag.kat = kat;

            List<SelectListItem> tur = (from x in db.Tbl_Tur.Where(x => x.Durum == true).ToList()
                                              select new SelectListItem
                                              {
                                                  Text = x.Turad,
                                                  Value = x.Id.ToString()
                                              }).ToList();
            ViewBag.tur = tur;

            List<SelectListItem> yonet = (from x in db.Tbl_Yonetmen.Where(x => x.Durum == true).ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.Ad + " " + x.Soyad,
                                              Value = x.Id.ToString()
                                          }).ToList();
            ViewBag.yonet = yonet;

            var bul = db.Tbl_Filmdizi.Find(id);
            return View("Guncelle", bul);
        }
        [HttpPost]
        public ActionResult Guncelle(Tbl_Filmdizi p)
        {
            var kat = db.Tbl_Kategori.Where(x => x.Id == p.Tbl_Kategori.Id).FirstOrDefault();
            var tur = db.Tbl_Tur.Where(x => x.Id == p.Tbl_Tur.Id).FirstOrDefault();
            var yonet = db.Tbl_Yonetmen.Where(x => x.Id == p.Tbl_Yonetmen.Id).FirstOrDefault();
            var deger = db.Tbl_Filmdizi.FirstOrDefault(x => x.Id == p.Id);
            deger.Detay = p.Detay;
            deger.Ad = p.Ad;
            deger.Foto = p.Foto;
            deger.Turid = tur.Id;
            deger.Katid = kat.Id;
            deger.Yonetmenid = yonet.Id;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

DiziFilmSatis/Views/Satis/Detay.cshtml
@model DiziFilmSatis.Models.Entity.Tbl_Filmdizi
@{
    ViewBag.Title = "Detay";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<div style="margin-top:20px;">
    <h3 style="color:cadetblue;">Eser Detay Sayfası</h3>
</div>
<form class="form-group">
    <div style="margin-top:20px;">
        <label>Eser Adı:</label>
        @Html.TextBoxFor(x => x.Ad, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Kategori:</label>
        @Html.TextBoxFor(x => x.Tbl_Kategori.Katad, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Tür:</label>
        @Html.TextBoxFor(x => x.Tbl_Tur.Turad, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Yönetmen Adı:</label>
        @Html.TextBoxFor(x => x.Tbl_Yonetmen.Ad, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Yönetmen Soyad:</label>
        @Html.TextBoxFor(x => x.Tbl_Yonetmen.Soyad, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Durum:</label>
        @Html.TextBoxFor(x => x.Durum, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Görsel:</label>
        @Html.TextBoxFor(x => x.Foto, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Detay:</label>
        @Html.TextAreaFor(x => x.Detay, new { @class = "form-control", @readonly = "readonly",@style="height:100px" })
    </div>
</form>

DiziFilmSatis/Views/Satis/Ekle.cshtml
@model DiziFilmSatis.Models.Entity.Tbl_Filmdizi
@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style="margin-top:20px;">
    <h3 style="color:cadetblue;">Dizi - Film Ekleme</h3>
</div>
<form method="post" class="form-group" enctype="multipart/form-data">
    <div style="margin-top:20px;">
        <label>Eser Adı:</label>
        <input type="text" name="Ad" value="" class="form-control" required=""/>
    </div>
    <div style="margin-top:20px;">
        <label>Kategori:</label>
        @Html.DropDownListFor(x=>x.Tbl_Kategori.Id, (List<SelectListItem>)ViewBag.kat,"Lütfen Kategori Seçiniz" ,new {@class="form-control",@required="required"})
    </div>
    <div style="margin-top:20px;">
        <label>Tür:</label>
        @Html.DropDownListFor(x=>x.Tbl_Tur.Id, (List<SelectListItem>)ViewBag.tur,"Lütfen Tür Seçiniz", new {@class="form-control", @required="required"})
    </div>
    <div style="margin-top:20px;">
        <label>Yönetmen:</label>
        @Html.DropDownListFor(x=>x.Tbl_Yonetmen.Id, (List<SelectListItem>)ViewBag.yonet,"Lütfen Yönetmen Seçiniz", new {@class="form-control",@required="required"})
    </div>
    <div style="margin-top:20px;">
        <label>Görsel:</label>
        <input type="text" name="Foto" value="" required="" class="form-control"/>
    </div>
    <div style="margin-top:20px;">
        <label>Detay:</label>
        <textarea class="form-control" required="" style="height:125px;" name="Detay"></textarea>
    </div>
    <div style="margin-top:20px;">
        <button class="btn btn-primary">Dizi-Film Ekle</button>
    </div>
</form>

DiziFilmSatis/Views/Satis/Guncelle.cshtml
@model DiziFilmSatis.Models.Entity.Tbl_Filmdizi
@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style="margin-top:20px;">
    <h3 style="color:cadetblue">Dizi - Film Güncelleme Sayfası</h3>
</div>
@using (Html.BeginForm("Guncelle", "Satis", FormMethod.Post))
 {
    <table class="table table-hover">
        <tr>
            <td><label>Dizi - Film Adı:</label></td>
            <td>
                @Html.TextBoxFor(x => x.Ad, new { @class = "form-control", @required = "required" })
            </td>
        </tr>
        <tr>
            <td><label>Kategori:</label></td>
            <td>
                @Html.DropDownListFor(x => x.Tbl_Kategori.Id, (List<SelectListItem>)ViewBag.kat, "Lütfen Kategori Seçiniz", new { @class = "form-control", @required = "required" })
            </td>
        </tr>
        <tr>
            <td><label>Tür:</label></td>
            <td>
                @Html.DropDownListFor(x => x.Tbl_Tur.Id, (List<SelectListItem>)ViewBag.tur, "Lütfen Yönetmen Seçiniz", new { @class = "form-control", @required = "required" })
            </td>
        </tr>
        <tr>
            <td><label>Yönetmen:</label></td>
            <td>
                @Html.DropDownListFor(x => x.Tbl_Yonetmen.Id, (List<SelectListItem>)ViewBag.yonet, "Lütfen Yönetmen Seçiniz", new { @class = "form-control", @required = "required" })
            </td>
        </tr>
        <tr>
            <td><label>Görsel:</label></td>
            <td>
                @Html.TextBoxFor(x => x.Foto, new { @class = "form-control", @required = "required" })
            </td>
        </tr>
        <tr>
            <td><label>Detay:</label></td>
            <td>
                @Html.TextAreaFor(x => x.Detay, new { @class = "form-control", @required = "required", @style="height:125px;" })
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <button class="btn btn-primary">Dizi - Film Güncelle</button>
            </td>
        </tr>
    </table>
}

DiziFilmSatis/Views/Satis/Index.cshtml
@using DiziFilmSatis.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Tbl_Filmdizi>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-striped" style="margin-top:10px;">
    <tr style="background-color:rgb(252,178,22)">
        <th>Id</th>
        <th>Eser Adı</th>
        <th>Kategori</th>
        <th>Tür</th>
        <th>Yönetmen</th>
        <th>Durum</th>
        <th>Güncelle</th>
        <th>Detay</th>
    </tr>
    <tbody>
        @{ string durum = "";}
        @foreach (var x in Model)
        {
            if (x.Durum == true)
            {
                durum = "Aktif";
            }
            if (x.Durum == false)
            {
                durum = "Pasif";
            }
            <tr>
                <td>@x.Id</td>
                <td>@x.Ad</td>
                <td>@x.Tbl_Kategori.Katad</td>
                <td>@x.Tbl_Tur.Turad</td>
                <td>
                    <a href="/Satis/Yonetmen/@x.Tbl_Yonetmen.Id">@x.Tbl_Yonetmen.Ad @x.Tbl_Yonetmen.Soyad</a>
                </td>
                <td>@durum</td>
                <td>
                    <a href="/Satis/Guncelle/@x.Id" class="btn btn-success">Eser Güncelle</a>
                </td>
                <td>
                    <a href="/Satis/Detay/@x.Id" class="btn btn-info">Eser Detay</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }), new PagedListRenderOptions
{
    LiElementClasses = new List<string>
    {"page-link"}
})

<div style="margin-top:10px;">
    <a href="/Satis/Ekle/" class="btn btn-group" style="background-color:purple; color:white;">Eser Ekle</a>
</div>