DiziFilmSatis/Controllers/MesajController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DiziFilmSatis.Models.Entity;
namespace DiziFilmSatis.Controllers
{
    public class MesajController : Controller
    {
        // GET: Mesaj
        Db_DiziFilmSatisEntities db = new Db_DiziFilmSatisEntities();
        public ActionResult Index()
        {
            var mesaj = db.Tbl_Mesaj.OrderByDescending(x=>x.Id).ToList();
            return View(mesaj);
        }
        public ActionResult Sil(int id)
        {
            var sil = db.Tbl_Mesaj.Find(id);
            db.Tbl_Mesaj.Remove(sil);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Detay(int id)
        {
            var bul = db.Tbl_Mesaj.FirstOrDefault(x => x.Id == id);
            return View("Detay", bul);
        }
        [HttpGet]
        public ActionResult Ekle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Ekle(Tbl_Mesaj p)
        {
            db.Tbl_Mesaj.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

DiziFilmSatis/Controllers/VitrinController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using DiziFilmSatis.Models.Entity;
namespace DiziFilmSatis.Controllers
{
    public class VitrinController : Controller
    {
        // GET: Vitrin
        Db_DiziFilmSatisEntities db = new Db_DiziFilmSatisEntities();
        public ActionResult Index()
        {
            var film = db.Tbl_Filmdizi.OrderByDescending(x => x.Id).Take(6).ToList();
            return View(film);
        }
        public PartialViewResult About()
        {
            var hakkkımzda = db.Tbl_Hakkimizda.ToList();
            return PartialView(hakkkımzda); 
        }
        [HttpGet]
        public PartialViewResult Mesaj()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult Mesaj(Tbl_Mesaj p)
        {
            p.Alıcı = "Admin@gmail.com";
            p.Tarih = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            db.Tbl_Mesaj.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

DiziFilmSatis/Views/Vitrin/About.cshtml
@using DiziFilmSatis.Models.Entity
@model List<Tbl_Hakkimizda>
<section class="page-section bg-primary text-white mb-0" id="about">
    <div class="container">

        <!-- About Section Heading -->
        <h2 class="page-section-heading text-center text-uppercase text-white">Hakkımızda</h2>

        <!-- Icon Divider -->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>

        <!-- About Section Content -->
        <div class="row">
            @foreach (var x in Model)
            {
                <div class="col-lg-4 ml-auto">
                    <p class="lead">@x.icerik1</p>
                </div>
                <div class="col-lg-4 mr-auto">
                    <p class="lead">@x.icerik2</p>
                </div>


            }
        </div>

        <div class="text-center mt-4">
            <a class="btn btn-xl btn-outline-light" href="https://startbootstrap.com/themes/freelancer/">
                <i class="fas fa-download mr-2"></i>
                Free Download!
            </a>
        </div>
        

    </div>
</section>

DiziFilmSatis/Views/Vitrin/Index.cshtml
@using DiziFilmSatis.Models.Entity
@model List<Tbl_Filmdizi>
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dizi - Film Satış</title>

    <!-- Custom fonts for this theme -->
    <link href="~/web/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Theme CSS -->
    <link href="~/web/css/freelancer.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">MVC5 DİZİ - FİLM SİTESİ </a>
            <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#portfolio">DİZİ - FİLM</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#about">Hakkımızda</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#contact">İLETİŞİM</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/Register/Index/">GİRİŞ YAP</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Masthead -->
    <header class="masthead bg-primary text-white text-center">
        <div class="container d-flex align-items-center flex-column">

            <!-- Masthead Avatar Image -->
            <img class="masthead-avatar mb-5" src="~/web/img/avataaars.svg" alt="">

            <!-- Masthead Heading -->
            <h1 class="masthead-heading text-uppercase mb-0">SİTEMİZE HOŞGELDİNİZ...</h1>

            <!-- Icon Divider -->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                    <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
            </div>

            <!-- Masthead Subheading -->
            <p class="masthead-subheading font-weight-light mb-0">Rüyadayken gördüklerimiz bize gerçek gibi gelir. Ancak uyandığımızda bir tuhaflık olduğunu fark ederiz.</p>

        </div>
    </header>

    <!-- Portfolio Section -->
    <section class="page-section portfolio" id="portfolio">
        <div class="container">

            <!-- Portfolio Section Heading -->
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">VİTRİN</h2>

            <!-- Icon Divider -->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                    <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
            </div>

            <!-- Portfolio Grid Items -->
            <div class="row">

                <!-- Portfolio Item 1 -->
                @foreach (var x in Model)
                {<div class="col-md-6 col-lg-4">
                        <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal@(x.Id)">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white">
                                    <i class="fas fa-plus fa-3x"></i>
                                </div>
                            </div>
                            <img class="img-fluid" src="@x.Foto" alt="" style="width:500px; height:400px;">
                        </div>
                    </div>    
                 }


                <!-- Portfolio Item 2 -->

            </div>
            <!-- /.row -->

        </div>
    </section>

    <!-- About Section -->
    @Html.Action("About")
    <!-- Contact Section -->
    @Html.Action("Mesaj")
    <!-- Footer -->
    <footer class="footer text-center">
        <div class="container">
            <div class="row">

                <!-- Footer Location -->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Location</h4>
                    <p class="lead mb-0">
                        2215 John Daniel Drive
                        <br>Clark, MO 65243
                    </p>
                </div>

                <!-- Footer Social Icons -->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Around the Web</h4>
                    <a class="btn btn-outline-light btn-social mx-1" href="#">
                        <i class="fab fa-fw fa-facebook-f"></i>
                    </a>
                    <a class="btn btn-outline-light btn-social mx-1" href="#">
                        <i class="fab fa-fw fa-twitter"></i>
                    </a>
                    <a class="btn btn-outline-light btn-social mx-1" href="#">
                        <i class="fab fa-fw fa-linkedin-in"></i>
                    </a>
                    <a class="btn btn-outline-light btn-social mx-1" href="#">
                        <i class="fab fa-fw fa-dribbble"></i>
                    </a>
                </div>

                <!-- Footer About Text -->
                <div class="col-lg-4">
                    <h4 class="text-uppercase mb-4">About Freelancer</h4>
                    <p class="lead mb-0">
                        Freelance is a free to use, MIT licensed Bootstrap theme created by
                        <a href="http://startbootstrap.com">Start Bootstrap</a>.
                    </p>
                </div>

            </div>
        </div>
    </footer>

    <!-- Copyright Section -->
    <section class="copyright py-4 text-center text-white">
        <div class="container">
            <small>Copyright &copy; Your Website 2019</small>
        </div>
    </section>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-to-top d-lg-none position-fixed ">
        <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>

    <!-- Portfolio Modals -->
    <!-- Portfolio Modal 1 -->
    @foreach(var x in Model) {
        <div class="portfolio-modal modal fade" id="portfolioModal@(x.Id)" tabindex="-1" role="dialog" aria-labelledby="portfolioModal1Label" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">
                    <i class="fas fa-times"></i>
                </span>
            </button>
            <div class="modal-body text-center">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-8">
                            <!-- Portfolio Modal - Title -->
                            <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">@x.Ad</h2>
                            <!-- Icon Divider -->
                            <div class="divider-custom">
                                <div class="divider-custom-line"></div>
                                <div class="divider-custom-icon">
                                    <i class="fas fa-star"></i>
                                </div>
                                <div class="divider-custom-line"></div>
                            </div>
                            <!-- Portfolio Modal - Image -->
                            <img class="img-fluid rounded mb-5" src="@x.Foto" alt="" style="height:400px;">
                            <!-- Portfolio Modal - Text -->
                            <p class="mb-5">@x.Detay</p>
                            <button class="btn btn-primary" href="#" data-dismiss="modal">
                                <i class="fas fa-times fa-fw"></i>
                                Pencereyi Kapat
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> }
    

    <!-- Portfolio Modal 2 -->
    

    <!-- Bootstrap core JavaScript -->
    <script src="~/web/vendor/jquery/jquery.min.js"></script>
    <script src="~/web/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="~/web/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="~/web/js/jqBootstrapValidation.js"></script>
    <script src="~/web/js/contact_me.js"></script>

    <!-- Custom scripts for this template -->
    <script src="~/web/js/freelancer.min.js"></script>

</body>

</html>

DiziFilmSatis/Views/Vitrin/Mesaj.cshtml
<section class="page-section" id="contact">
    <div class="container">

        <!-- Contact Section Heading -->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">BİZE Ulaşın</h2>

        <!-- Icon Divider -->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>

        <!-- Contact Section Form -->
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                @using (Html.BeginForm("Mesaj", "Vitrin", FormMethod.Post)) {
                <form name="sentMessage" id="contactForm" novalidate="novalidate" >
                    <div class="control-group">
                        <div class="form-group floating-label-form-group controls mb-0 pb-2">
                            <label>İsim</label>
                            <input class="form-control" id="name" type="text" placeholder="İsim" required="required" data-validation-required-message="Please enter your name." name="Name">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="form-group floating-label-form-group controls mb-0 pb-2">
                            <label>Mail Adresi</label>
                            <input class="form-control" id="email" type="email" placeholder="Mail Adresi" required="required" data-validation-required-message="Please enter your email address." name="Mail">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="form-group floating-label-form-group controls mb-0 pb-2">
                            <label>Konu</label>
                            <input class="form-control" id="phone"  placeholder="Konu" required="required" data-validation-required-message="Please enter your phone number." name="Konu">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="form-group floating-label-form-group controls mb-0 pb-2">
                            <label>Mesaj</label>
                            <textarea class="form-control" id="message" rows="5" placeholder="Mesaj" required="required" data-validation-required-message="Please enter a message." name="Mesaj"></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-xl" id="sendMessageButton">Mesaj Gönder</button>
                    </div>
                </form>
                }
            </div>
        </div>

    </div>
</section>