DiziFilmSatis/Controllers/TurController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DiziFilmSatis.Models.Entity;
namespace DiziFilmSatis.Controllers
{
    public class TurController : Controller
    {
        // GET: Tur
        Db_DiziFilmSatisEntities db = new Db_DiziFilmSatisEntities();
        public ActionResult Index()
        {
            var tur = db.Tbl_Tur.ToList();
            return View(tur);
        }
        public ActionResult Aktif(int id)
        {
            var bul = db.Tbl_Tur.Find(id);
            bul.Durum = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Pasif(int id)
        {
            var bul = db.Tbl_Tur.Find(id);
            bul.Durum = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Ekle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Ekle(Tbl_Tur p)
        {
            p.Durum = true;
            db.Tbl_Tur.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Guncelle(int id)
        {
            var bul = db.Tbl_Tur.Find(id);
            return View("Guncelle", bul);
        }
        [HttpPost]
        public ActionResult Guncelle(Tbl_Tur p)
        {
            var bul = db.Tbl_Tur.FirstOrDefault(x => x.Id == p.Id);
            bul.Durum = true;
            bul.Turad = p.Turad;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

DiziFilmSatis/Views/Tur/Guncelle.cshtml
@model DiziFilmSatis.Models.Entity.Tbl_Tur
@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style="margin-top:20px;">
    <h3 style="color:cadetblue;">Tür Güncelleme Sayfası</h3>
</div>
@using (Html.BeginForm("Guncelle","Tur",FormMethod.Post, new {@class="form-group"}))
 {
    <div style="margin-top:20px;">
        <label>Tür Id:</label>
        @Html.TextBoxFor(x=>x.Id, new {@class="form-control", @readonly="readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Tür Adı:</label>
        @Html.TextBoxFor(x=>x.Turad, new  { @class="form-control", @required="required"})
    </div>
    <div style="margin-top:20px;">
        <button class="btn btn-primary">Tür Güncelle</button>
    </div>
 }

DiziFilmSatis/Views/Tur/Index.cshtml
@using DiziFilmSatis.Models.Entity
@model List<Tbl_Tur>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-striped" style="margin-top:10px;">
    <tr style="background-color:rgb(252,178,22)">
        <th>Id</th>
        <th>Tür</th>
        <th>Durum</th>
        <th>İşlemler</th>
        <th>Güncelle</th>
    </tr> 
    <tbody>
        @{ string durum = "";string yazı = ""; string buton=""; string link = "";}
        @foreach(var x in Model)
        {
            if(x.Durum == true)
            {
                durum = "Aktif";
                yazı = "Pasif Yap";
                buton = "btn btn-outline-danger";
                link = "/Tur/Pasif";

            }
            if(x.Durum== false)
            {
                durum = "Pasif";
                yazı = "Aktif Yap";
                buton = "btn btn-outline-primary";
                link = "/Tur/Aktif";
            }
                <tr>
                    <td>@x.Id</td>
                    <td>@x.Turad</td>
                    <td>@durum</td>
                    <td>
                        <a href="@link/@x.Id" class="@buton">@yazı</a>
                    </td>
                    <td>
                        <a href="/Tur/Guncelle/@x.Id" class="btn btn-success">Tür Güncelle</a>
                    </td>
                </tr>
            }
    </tbody>
</table>

<button class="btn btn-group" style="background-color:purple; color:white; margin-top:10px;" data-toggle="modal" data-target="#Modal1" >Tür Ekle</button>
<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Tür Ekleme Paneli</h3>
            </div>
            <form class="form-group" method="post" action="/Tur/Ekle/">
                <div class="modal-body">
                    <label>Tür Adı:</label>
                    <input type="text" name="Turad" class="form-control" required="" />
                    <br />
                    <button class="btn btn-info">Tür Ekle</button>
                </div>
            </form>
        </div>
    </div>
</div>